name: Initialize FFmpeg Configuration

on:
  workflow_call:
    inputs:
      github_tag:
        description: 'FFmpeg version from checked out source'
        required: true
        type: string
      build_type:
        description: 'Build type of included libraries'
        required: true
        type: string
      link_type:
        description: 'Link type of libraries'
        required: true
        type: string
      msystem:
        description: 'MSYS Environment'
        required: true
        type: string
      major_version:
        description: 'Version'
        required: true
        type: string
    outputs:
      output_path:
        description: 'Add bits to FFmpeg config setup'
        value: ${{ jobs.setup-ffmpeg-options.outputs.output_path }}
      build_file_ref:
        description: 'Filename of readme file included with generated build archive'
        value: ${{ jobs.setup-ffmpeg-options.outputs.build_file_ref }}
      version_name:
        description: 'Version header string'
        value: ${{ jobs.setup-ffmpeg-options.outputs.version_name }}
      build_config:
        description: 'Updated build configuration'
        value: ${{ jobs.setup-ffmpeg-options.outputs.build_config }}

env:
  build_config: ""

jobs:
  setup-ffmpeg-options:
    name: '🎞️ Initialize FFmpeg Configuration'
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    outputs:
      output_path: ${{ steps.output-path.outputs.output_path }}
      build_file_ref: ${{ steps.build-file-ref.outputs.build_file_ref }}
      version_name: ${{ steps.version-name.outputs.version_name }}
      build_config: ${{ steps.build-config.outputs.build_config }}
    steps:
    - name: '🛒 Checkout'
      uses: actions/checkout@v6
    - name: '🗺️ Setup Configuration'
      id: 'baseline'
      working-directory: ./config
      run: |
        base_config=$(jq -r '.config' options.json)
        echo "build_config=${base_config}" >> $GITHUB_ENV
    - name: '🏛️ Set Target Architecture'
      id: 'arch'
      run: |
        echo "📢 Set Explict Architecture Option Value"
        if [[ ${{ inputs.msystem }} == "CLANGARM64" ]]; then
          temp_config=" --arch=aarch64"
        elif [[ ${{ inputs.msystem }} == "CLANG64" ]]; then
          temp_config="--arch=x86_64"
        fi
        echo "build_config=$build_config$temp_config" >> $GITHUB_ENV
    - name: '🔗 Set Link Type'
      id: 'link_type'
      run: |
        echo "📢 Set Explict Linking"
        if [[ ${{ inputs.link_type }} == "shared" ]]; then
          temp_config=" --enable-shared --disable-static"
        else
          temp_config=" --disable-shared --enable-static"
        fi
        echo "build_config=$build_config$temp_config" >> $GITHUB_ENV
    - name: '🏴 Set Extra LDFLAGS'
      id: 'flags'
      working-directory: ./config
      run: |
        echo "📢 Set Additional Linker Flags"
        if [[ ${{ inputs.build_type }} == "full" ]]; then
          temp_config=" --extra-ldflags='-Wl,--allow-multiple-definition'"
          temp_config+=" --extra-cflags=-DLIBTWOLAME_STATIC"
          echo "build_config=$build_config$temp_config" >> $GITHUB_ENV
        fi
    - name: '🏴 Set Initial FFmpeg Build Config'
      id: 'config'
      working-directory: ./config
      run: |
        echo "📢 build_config: $build_config"
        echo "build_config=$build_config" >> $GITHUB_OUTPUT
    - name: '🧭 Build output path'
      id: 'output-path'
      shell: bash
      run: |
        echo "📢 Define path for build output (prefix)"
        runner_path="/d/a/"
        msys_path="/c/a/"
        path=$(pwd)
        path="${path}/builds/ffmpeg-${{ inputs.link_type }}"
        path="${path//$runner_path/$msys_path}"
        echo "📢 output_path: $path"
        echo "output_path=${path}" >> $GITHUB_OUTPUT
    - name: '🪢 Make Version Name String'
      id: 'version-name'
      shell: bash
      run: |
        echo "📢 Make a version name string for headers and archive file naming"
        shopt -s extglob
        cpu="arm64"
        if [[ ${{ inputs.msystem }} == "CLANG64" ]]; then
          cpu="x64"
        fi
        version_string="${{ inputs.github_tag }}"
        version_string="${version_string##+([[:alpha:]])}"
        version_name="ffmpeg-$version_string-${{ inputs.build_type }}-${{ inputs.link_type }}-win-${cpu}"
        echo "📢 version_name: $version_name"
        echo "version_name=${version_name}" >> $GITHUB_OUTPUT
    - name: '📃 Make Temporary Readme Filename'
      id: 'build-file-ref'
      shell: bash
      run: |
        echo "📢 Direct configure command stdout to a text file."
        echo "📢 Use text file as readme.txt inside distribution package."
        echo "📢 Make a temporary file name for later copying."
        build_file_ref="${{ inputs.build_type}}-${{ inputs.link_type }}.txt"
        echo "📢 build_file_ref: $build_file_ref"
        echo "build_file_ref=${build_file_ref}" >> $GITHUB_OUTPUT
    - name: '☑️ Verify Config Settings'
      id: 'build-config'
      shell: bash
      run: |
        echo "📢 Update FFmpeg build config with distribution specific settings"
        temp_config="${{ env.build_config }}"
        temp_config+=" --prefix=${{ steps.output-path.outputs.output_path }}/${{ steps.version-name.outputs.version_name }}"
        temp_config+=" --datadir=${{ steps.output-path.outputs.output_path }}/${{ steps.version-name.outputs.version_name }}/presets"
        temp_config+=" --docdir=${{ steps.output-path.outputs.output_path }}/${{ steps.version-name.outputs.version_name }}/docs"
        temp_config+=" --libdir=${{ steps.output-path.outputs.output_path }}/dump/libs"
        temp_config+=" --incdir=${{ steps.output-path.outputs.output_path }}/dump/include"
        echo "📢 temp_config: $temp_config"
        echo "build_config=${temp_config}" >> $GITHUB_OUTPUT